version: '3.8'

services:
  prometheus:
    image: ubuntu/prometheus:latest
    container_name: prometheus-container
    networks:
      - monitoring
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    environment:
      - TZ=UTC

  grafana:
    image: grafana/grafana:8.5.5
    container_name: grafana
    networks:
      - monitoring
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - TZ=UTC

  influxdb:
    image: influxdb:1.11.7-alpine
    container_name: influxdb2
    networks:
      - monitoring
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - TZ=UTC

  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    networks:
      - monitoring
    ports:
      - "8080:8080"
    volumes:
      - jenkins_data:/var/lib/jenkins
    environment:
      - TZ=UTC

volumes:
  grafana_data:
    driver: local
  influxdb_data:
    driver: local
  jenkins_data:
     driver: local

networks:
  monitoring:
    driver: bridge

